BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE sale';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE customer';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE product';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE salesperson';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE manufacturer';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
